name: Build EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar c√≥digo
        uses: actions/checkout@v2

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar nexe
        run: npm install -g nexe

      - name: Compilar para EXE
        run: nexe index.js --output app.exe

      - name: Upload do EXE
        uses: actions/upload-artifact@v2  # Mudado de v3 para v2
        with:
          name: app-exe
          path: app.exe
